server:
  port: 9090

spring:
  application:
    name: owasp-demo
#  security:
#    user:
#      name: user
#      password: password
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect